# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g.,[user1, user2]
patreon: vbpixel
open_collective: vbpixel
ko_fi: vbpixel
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: vbpixel
issuehunt: vbpixel
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee:
thanks_dev: # Replace with a single thanks.dev username
custom: https://afdian.com/a/MCVBPIXEL
