name: delete deploy preview

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  Get-Deploy-IDs:
    runs-on: ubuntu-latest
    outputs:
      deploy_ids: ${{ steps.get-value.outputs.deploy_ids }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install @actions/github @actions/core
      - name: Get values from comments
        id: get-value
        run: node .github/workflows/js/get-value.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Call-Api:
    runs-on: ubuntu-latest
    needs: Get-Deploy-IDs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Call API for each deploy ID
        run: |
          deploy_ids=(${{ needs.Get-Deploy-IDs.outputs.deploy_ids }})
          for deploy_id in "${deploy_ids[@]}"; do
            echo "Deleting deploy ID: $deploy_id"
            if ! netlify api deleteSiteDeploy --data "{\"deploy_id\": \"$deploy_id\", \"site_id\": \"${{ secrets.NETLIFY_SITE_ID }}\"}"; then
              echo "deploy ID:$deploy_id删除失败, 继续删除下一个"
            fi
          done
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
